name: Interlis-tests

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  interlis-tests:
    name: Interlis-tests
    runs-on: ubuntu-20.04
    strategy:
        fail-fast: false
        matrix:
            suite: ["qgep", "qwat"]
            postgis:
              - postgis/postgis:13-3.2
              - postgis/postgis:12-3.0

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
            python-version: 3.8

      - name: Install python deps
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest qgepqwat2ili.tests.test_$SUITE
        env:
            SUITE: ${{ matrix.suite }}
            QGEPQWAT2ILI_TESTDB_IMAGE: ${{ matrix.postgis }}
            PGHOST: 127.0.0.1
            PGPORT: 5432
            PGDATABASE: qgep_prod
            PGUSER: postgres
            PGPASS: postgres
